### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Zenobian** [rgamici/anki_plugin_jaja_definitions#1]
Sorry, don't know where I can ask questions

> Error 
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
> If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
> When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
> Debug info:
> Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
> Platform: Windows 7
> Flags: frz=True ao=True sv=1
> 
> Traceback (most recent call last):
>   File "C:\Users\Zenobian\AppData\Roaming\Anki2\addons21\2055037404\__init__.py", line 82, in regenGlosses
>     glossNote(f)
>   File "C:\Users\Zenobian\AppData\Roaming\Anki2\addons21\2055037404\__init__.py", line 61, in glossNote
>     f[jap_defField] = fetchDef(f[expressionField])
>   File "C:\Users\Zenobian\AppData\Roaming\Anki2\addons21\2055037404\__init__.py", line 36, in fetchDef
>     response = urllib.request.urlopen(pageUrl)
>   File "urllib\request.py", line 223, in urlopen
>   File "urllib\request.py", line 532, in open
>   File "urllib\request.py", line 642, in http_response
>   File "urllib\request.py", line 570, in error
>   File "urllib\request.py", line 504, in _call_chain
>   File "urllib\request.py", line 650, in http_error_default
> urllib.error.HTTPError: HTTP Error 404: 404

**Comment by rgamici** [comment]
Thank you for reporting it.

It was working fine a week ago.
It looks like there was a change in the dictionary website that broke the addon.

I've fixed it and it is working again for me.
I also uploaded the updated version to the Anki website.
I'm not sure if it automatically updates the addons or if you need to do it manually (or uninstall and re-install it).

Please let me know if it works for you.

**Comment by Zenobian** [comment]
Yep, it works fine now. Thanks!
