### ISSUE TITLE
Not functional

### ISSUE THREAD

**Issue by ghost** [rgamici/anki_plugin_jaja_definitions#10]
Hello.
I can't seem to get the addon working. When I click regenerate definitions, it shows the anki loading bar for a bit and then disappears. When I check the field I specified it's empty
[Browser's selection.zip](https://github.com/rgamici/anki_plugin_jaja_definitions/files/3960393/Browser.s.selection.zip)
Even when I make a note type with the base 'Japanese' and 'JapaneseDefinition' fields, it does not work for me.

**Comment by rgamici** [comment]
Can you confirm that the deck you linked has only one card?

I noticed that it wasn't working when only one card is selected and already have filled bug #9 .
I edited your fields and it worked for me if I select two cards (I added a dummy one).
Have you selected only that card before clicking "Regenerate ..."?

I'm not sure how long it will take to fix #9, but a current workaround is to select another card and it will work.
If your note type has two cards, selecting at least two of the cards and clicking "Regenerate ..." should work.

It seems that if the note fields are shown it won't work.
![wontwork](https://user-images.githubusercontent.com/12600046/70811943-8c1e2900-1dbe-11ea-8d6c-0012546e0ae7.png)
But, if you select two cards/notes, the note fields will disappear, and it will work.
![work](https://user-images.githubusercontent.com/12600046/70812002-aa842480-1dbe-11ea-936a-91f4bcea1874.png)

**Comment by ghost** [comment]
I'm sorry about wasting your time. I did glance at that issue but I thought it meant a word as in a Kanji or something. Selecting multiple entries generated the definitions perfectly.

**Comment by rgamici** [comment]
Don't worry about it.
I wasn't expecting that anyone would comment, and because of that I only wrote it for me to remember to fix it later.

**Comment by rgamici** [comment]
@Cupbox, I've patched it and it seems to be working now if you select only a single note.

**Comment by ghost** [comment]
Thank you. Working perfectly now.
