### ISSUE TITLE
Separate config.json files for settings

### ISSUE THREAD

**Issue by ghost** [rgamici/anki_plugin_jaja_definitions#15]
Currently new updates require you to re-set custom fields.

**Comment by rgamici** [comment]
Is it the same as #7 ?
I've already committed a modification to do it, but I still haven't uploaded it to Anki's website.

**Comment by rgamici** [comment]
I hadn't realized that it was a big change for users, since I use the default fields, and I was planning to update it when I finished a few more stuff I wanted to implement/modify.
I have just uploaded the updated version on Anki's website, and it should solve this issue.

**Comment by ghost** [comment]
Thanks. This makes it much simpler.
